import{MONSTER_SLAYER_GOALS,type NormalizedSaveImport,type TrackerRecord}from'@stardew/game-data';
const text=(root:ParentNode|null,selector:string,fallback='')=>root?.querySelector(selector)?.textContent?.trim()||fallback;
const number=(root:ParentNode|null,selector:string,fallback=0)=>Number(text(root,selector,String(fallback)))||fallback;
const items=(root:ParentNode|null,selector:string)=>Array.from(root?.querySelectorAll(selector)||[]);
const dictionary=(root:ParentNode|null,name:string)=>items(root,`${name} > item`).map(node=>({key:text(node,'key > string')||text(node,'key > int'),node})).filter(x=>x.key);
const boolRecord=(domain:TrackerRecord['domain'],itemId:string,field:string):TrackerRecord=>({domain,itemId,value:{[field]:true}});
const normalizeId=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,'-');
const seasonName=(raw:string)=>({spring:'Spring',summer:'Summer',fall:'Fall',winter:'Winter'}[raw.toLowerCase()]||'Spring')as NormalizedSaveImport['season'];
async function hashFile(xml:string){const bytes=new TextEncoder().encode(xml);const digest=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(digest),x=>x.toString(16).padStart(2,'0')).join('')}
function parsePlayer(player:Element,isHost:boolean,index:number){const sourceId=text(player,'UniqueMultiplayerID',`${isHost?'host':'farmhand'}-${index}`);const records:TrackerRecord[]=[];
 for(const{key,node}of dictionary(player,'basicShipped'))if(number(node,'value > int')>0)records.push(boolRecord('shipping',key,'completed'));
 for(const{key,node}of dictionary(player,'recipesCooked'))if(number(node,'value > int')>0)records.push(boolRecord('cooking',key,'completed'));
 for(const{key,node}of dictionary(player,'craftingRecipes'))if(number(node,'value > int')>0)records.push(boolRecord('crafting',key,'completed'));
 for(const{key}of dictionary(player,'fishCaught'))records.push(boolRecord('fish',key,'completed'));
 for(const{key,node}of dictionary(player,'friendshipData')){const points=number(node,'value > Friendship > Points');records.push({domain:'relationships',itemId:key.toLowerCase().replace(/[^a-z0-9]+/g,'-'),value:{points,hearts:Math.min(14,Math.floor(points/250)),status:text(node,'value > Friendship > Status')}})}
 const levels=[['farming','farmingLevel'],['fishing','fishingLevel'],['foraging','foragingLevel'],['mining','miningLevel'],['combat','combatLevel']]as const;for(const[id,tag]of levels)records.push({domain:'skills',itemId:id,value:{level:number(player,tag)}});
 const mail=new Set(items(player,'mailReceived > string').map(x=>x.textContent?.trim()||''));for(const id of['CF_Fair','CF_Fish','CF_Mines','CF_Sewer','CF_Spouse','CF_Statue','museumComplete'])if(mail.has(id))records.push(boolRecord('stardrops',id,'completed'));
 const killed=new Map(dictionary(player,'stats > specificMonstersKilled').map(({key,node})=>[key,number(node,'value > int')]));for(const goal of MONSTER_SLAYER_GOALS){const count=goal.targets.reduce((sum,target)=>sum+(killed.get(target)||0),0);records.push({domain:'monster-goals',itemId:goal.id,value:{count,target:goal.count,completed:count>=goal.count}})}
 records.push({domain:'relationships',itemId:'household',value:{spouse:text(player,'spouse'),children:0,houseUpgrade:number(player,'houseUpgradeLevel')}});
 return{sourceId,name:text(player,'name',isHost?'Host':`Farmhand ${index}`),isHost,records};}
export async function parseSaveFile(file:File):Promise<NormalizedSaveImport>{if(file.size>20*1024*1024)throw new Error('Save files larger than 20 MB are not supported.');const xml=await file.text();const doc=new DOMParser().parseFromString(xml,'application/xml');if(doc.querySelector('parsererror')||!doc.querySelector('SaveGame'))throw new Error('This is not a valid Stardew Valley save XML file.');const root=doc.querySelector('SaveGame')!;const gameVersion=text(root,'gameVersion','1.6.0');if(!/^1\.6(?:\.\d+)?$/.test(gameVersion))throw new Error(`Stardew ${gameVersion} is not supported. Junimo Journal currently supports 1.6.x saves.`);
 const host=root.querySelector(':scope > player');if(!host)throw new Error('The save does not contain a host farmer.');const farmhands=[parsePlayer(host,true,0),...items(root,'farmhands Farmer').map((node,index)=>parsePlayer(node as Element,false,index+1))];const childCounts=new Map<string,number>();for(const npc of items(root,'characters > NPC')){if(Array.from((npc as Element).attributes).some(a=>a.value==='Child')){const parent=text(npc,'idOfParent');childCounts.set(parent,(childCounts.get(parent)||0)+1)}}for(const farmer of farmhands){const household=farmer.records.find(r=>r.domain==='relationships'&&r.itemId==='household');if(household)household.value.children=childCounts.get(farmer.sourceId)||0}const shared:TrackerRecord[]=[];
 const museum=items(root,'museumPieces > item');for(const piece of museum){const id=text(piece,'value > string')||text(piece,'value > int');if(id)shared.push(boolRecord('museum',id,'completed'))}
 let obelisks=0,clock=false;for(const building of items(root,'buildings > Building')){const type=text(building,'buildingType');if(['Water Obelisk','Earth Obelisk','Desert Obelisk','Island Obelisk'].includes(type)&&number(building,'daysOfConstructionLeft')<=0)obelisks++;if(type==='Gold Clock'&&number(building,'daysOfConstructionLeft')<=0)clock=true}shared.push({domain:'perfection',itemId:'farm',value:{obelisks,clock,waivers:number(root,'perfectionWaivers')}});
 for(const animal of items(root,'FarmAnimal')){const name=text(animal,'name','Unknown');const type=text(animal,'type','Animal');const id=text(animal,'myID',`${type}-${name}`).replace(/[^a-zA-Z0-9-]/g,'-');shared.push({domain:'animals',itemId:id,value:{name,type,age:number(animal,'age'),friendship:number(animal,'friendshipTowardFarmer'),happiness:number(animal,'happiness'),kind:'farm'}})}for(const pet of items(root,'characters > NPC')){const type=text(pet,'petType');if(!type)continue;const name=text(pet,'name','Pet');shared.push({domain:'animals',itemId:`pet-${normalizeId(name)}`,value:{name,type,friendship:number(pet,'friendshipTowardFarmer'),kind:'pet'}})}const horse=text(host,'horseName');if(horse)shared.push({domain:'animals',itemId:`horse-${normalizeId(horse)}`,value:{name:horse,type:'Horse',kind:'horse'}});
 const walnutCount=number(root,'goldenWalnutsFound',number(root,'GoldenWalnuts'));shared.push({domain:'walnuts',itemId:'total',value:{count:walnutCount}});
 const farmName=text(root,'farmName',text(host,'farmName','My Farm'));const warnings:string[]=[];if(farmhands.length>1)warnings.push(`${farmhands.length} farmhands detected. Map each farmer you want to import.`);return{fileHash:await hashFile(xml),gameVersion,farmName,season:seasonName(text(root,'currentSeason','spring')),day:number(root,'dayOfMonth',1),year:number(root,'year',1),shared,farmhands,warnings}}
