import{ACHIEVEMENTS,BUNDLE_ROOMS,COOKING_RECIPES,CRAFTING_RECIPES,FISH,ISLAND_UPGRADES,MONSTER_SLAYER_GOALS,JOURNAL_SCRAPS,MUSEUM_ITEMS,POWERS,RACCOON_REQUESTS,RARECROWS,SECRET_NOTES,SHIPPING_ITEMS,VILLAGERS,WALNUT_SOURCES,bundleSprite,objectName,type ImportedBundleLayout,type NormalizedSaveImport,type TrackerRecord}from'@stardew/game-data';
const text=(root:ParentNode|null,selector:string,fallback='')=>root?.querySelector(selector)?.textContent?.trim()||fallback;
const number=(root:ParentNode|null,selector:string,fallback=0)=>{const value=Number(text(root,selector,String(fallback)));return Number.isFinite(value)?value:fallback};
const items=(root:ParentNode|null,selector:string)=>Array.from(root?.querySelectorAll(selector)||[])as Element[];
const dictionary=(root:ParentNode|null,name:string)=>items(root,`${name} > item`).map(node=>({key:text(node,'key > string')||text(node,'key > int'),node})).filter(x=>x.key);
const list=(root:ParentNode|null,selector:string)=>items(root,selector).map(x=>x.textContent?.trim()||'').filter(Boolean);
const boolRecord=(domain:TrackerRecord['domain'],itemId:string,field='completed'):TrackerRecord=>({domain,itemId,value:{[field]:true}});
const normalizeId=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const unqualifiedId=(value:string)=>value.replace(/^\([^)]+\)/,'').replace(/^[A-Za-z]+:/,'');
const shippingIds=new Set<string>(SHIPPING_ITEMS.map(item=>item.id)),museumIds=new Set<string>(MUSEUM_ITEMS.map(item=>item.id)),rarecrowIdsCatalog=new Set<string>(RARECROWS.map(item=>item.id)),walnutIds=new Set<string>(WALNUT_SOURCES.map(item=>item.id)),achievementIds=new Set<string>(ACHIEVEMENTS.map(item=>item.id)),noteIds=new Set<string>(SECRET_NOTES.map(item=>item.id)),scrapIds=new Set<string>(JOURNAL_SCRAPS.map(item=>item.id)),villagerIds=new Set<string>(VILLAGERS.map(item=>item.id));
const seasonName=(raw:string)=>({spring:'Spring',summer:'Summer',fall:'Fall',winter:'Winter'}[raw.toLowerCase()]||'Spring')as NormalizedSaveImport['season'];
const hasType=(node:Element,type:string)=>Array.from(node.attributes).some(a=>a.localName==='type'&&a.value===type);
const stat=(player:Element,key:string)=>{const hit=dictionary(player,'stats > Values').find(row=>row.key===key);return hit?number(hit.node,'value > unsignedInt',number(hit.node,'value > int')):number(player,`stats > ${key}`)};
async function hashFile(xml:string){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(xml));return Array.from(new Uint8Array(digest),x=>x.toString(16).padStart(2,'0')).join('')}
function mailSet(player:Element,selector='mailReceived'){return new Set(list(player,`${selector} > string`))}
function parseBundleLayout(root:Element,hostMail:Set<string>){const joja=hostMail.has('jojaMember');if(joja){const projectNames:Record<string,string>={jojaCraftsRoom:'Bridge',jojaBoilerRoom:'Minecarts',jojaVault:'Bus',jojaPantry:'Greenhouse',jojaFishTank:'Panning',ccMovieTheaterJoja:'Movie Theater'};const projects=Object.keys(projectNames).filter(x=>hostMail.has(x)).map(x=>projectNames[x]);return{layout:{route:'joja',kind:'joja',rooms:[],jojaProjects:projects}as ImportedBundleLayout,status:[]as TrackerRecord[]}}
 const center=items(root,'locations > GameLocation').find(x=>hasType(x,'CommunityCenter'));const completion=new Map<string,boolean[]>();for(const row of dictionary(center||null,'bundles'))completion.set(row.key,items(row.node,'value boolean').map(x=>x.textContent?.trim()==='true'));
 const rooms=new Map<string,ImportedBundleLayout['rooms'][number]>();const statuses:TrackerRecord[]=[];const standardNames=new Set(BUNDLE_ROOMS.flatMap(r=>r.bundles.map(b=>b.name.replace(/ Bundle$/,''))));let remixed=false,randomized=false;
 for(const row of dictionary(root,'bundleData')){const [area,saveId]=row.key.split('/');const raw=text(row.node,'value > string');if(!area||saveId===undefined||!raw)continue;const parts=raw.split('/'),name=parts[0]||`Bundle ${saveId}`,rewardRaw=parts[1]||'',requirements=(parts[2]||'').trim().split(/\s+/).filter(Boolean),required=Number(parts[4]||-1);const rewardBits=rewardRaw.split(' '),reward=rewardRaw?`${objectName(unqualifiedId(rewardBits[1]||''))} ×${rewardBits[2]||1}`:'';const bundleItems=[];const done=completion.get(saveId)||[];
  for(let i=0,slot=0;i<requirements.length;i+=3,slot++){const gameId=unqualifiedId(requirements[i]),quantity=Number(requirements[i+1]||1),quality=Number(requirements[i+2]||0),itemName=gameId==='-1'?`${quantity.toLocaleString()}g`:objectName(gameId),iconPath=gameId==='-1'?`/game-icons/bundles/${quantity}.webp`:bundleSprite(gameId,itemName).iconPath||`/game-icons/objects/${gameId}.webp`;bundleItems.push({slot,gameId,name:itemName,quantity,quality,iconPath});statuses.push({domain:'bundles',itemId:`save:${saveId}:${slot}`,value:{completed:done[slot]===true}})}
  const roomId=normalizeId(area),room=rooms.get(roomId)||{id:roomId,name:area,bundles:[]};room.bundles.push({saveId,stableKey:`${roomId}:${normalizeId(name)}`,name,reward,required:required<0?bundleItems.length:required,items:bundleItems});rooms.set(roomId,room);if(!standardNames.has(name.replace(/ Bundle$/,'')))remixed=true}
 const roomList=[...rooms.values()];const layout:ImportedBundleLayout={route:'community-center',kind:roomList.length?(randomized?'randomized':remixed?'remixed':'standard'):'empty',rooms:roomList};return{layout,status:statuses}}
function parsePlayer(player:Element,host:Element,isHost:boolean,index:number){const sourceId=text(player,'UniqueMultiplayerID',`${isHost?'host':'farmhand'}-${index}`),records:TrackerRecord[]=[];
 for(const{key,node}of dictionary(player,'basicShipped')){const id=unqualifiedId(key);if(number(node,'value > int')>0&&shippingIds.has(id))records.push(boolRecord('shipping',id))}for(const{key,node}of dictionary(player,'recipesCooked'))if(number(node,'value > int')>0){const id=unqualifiedId(key),recipe=COOKING_RECIPES.find(row=>row.id===id||row.name===key);if(recipe)records.push(boolRecord('cooking',recipe.id))}const craftAliases:Record<string,string>={'Transmute (Fe)':'Iron Bar','Transmute (Au)':'Gold Bar','Wild Seeds (Sp)':'Spring Seeds','Wild Seeds (Su)':'Summer Seeds','Wild Seeds (Fa)':'Fall Seeds','Wild Seeds (Wi)':'Winter Seeds','Oil Of Garlic':'Oil of Garlic'};for(const{key,node}of dictionary(player,'craftingRecipes'))if(number(node,'value > int')>0){const name=craftAliases[key]||key,recipe=CRAFTING_RECIPES.find(row=>row.id===key||row.name===name);if(recipe)records.push(boolRecord('crafting',recipe.id))}for(const{key}of dictionary(player,'fishCaught')){const id=unqualifiedId(key),fish=FISH.find(row=>row.gameId===id||row.id===id);if(fish)records.push(boolRecord('fish',fish.id))}
 for(const{key,node}of dictionary(player,'friendshipData')){const id=normalizeId(key),points=number(node,'value > Friendship > Points');if(villagerIds.has(id))records.push({domain:'relationships',itemId:id,value:{points,hearts:Math.min(14,Math.floor(points/250)),status:text(node,'value > Friendship > Status')}})}
 const xp=list(player,'experiencePoints > int').map(Number),levels=[['farming','farmingLevel'],['fishing','fishingLevel'],['foraging','foragingLevel'],['mining','miningLevel'],['combat','combatLevel']]as const;for(const[id,tag]of levels)records.push({domain:'skills',itemId:id,value:{level:number(player,tag),xp:xp[levels.findIndex(x=>x[0]===id)]||0}});records.push({domain:'skills',itemId:'mastery',value:{xp:stat(player,'MasteryExp'),professions:list(player,'professions > int').map(Number)}});
 const received=mailSet(player),tomorrow=mailSet(player,'mailForTomorrow'),mailbox=mailSet(player,'mailbox'),hostMail=mailSet(host),events=new Set(list(player,'eventsSeen > int'));for(const id of['CF_Fair','CF_Fish','CF_Mines','CF_Sewer','CF_Spouse','CF_Statue','museumComplete'])if(received.has(id))records.push(boolRecord('stardrops',id));for(const achievement of list(player,'achievements > int'))if(achievementIds.has(achievement))records.push(boolRecord('achievements',achievement));records.push({domain:'farmer',itemId:'events',value:{ids:[...events].slice(0,5000)}});records.push({domain:'farmer',itemId:'mail-flags',value:{ids:[...received].slice(0,5000)}});
 for(const power of POWERS){const mails=power.playerKey==='Host'?hostMail:new Set([...received,...tomorrow,...mailbox]);const complete=power.type==='mail'?mails.has(power.flag):power.type==='event'?events.has(power.flag):stat(player,power.flag)>0;if(complete)records.push(boolRecord('powers',power.id))}
 for(const raw of list(player,'secretNotesSeen > int')){if(noteIds.has(raw))records.push(boolRecord('notes',raw,'found'));if(scrapIds.has(raw))records.push(boolRecord('scraps',raw,'found'))}for(const upgrade of ISLAND_UPGRADES)if(received.has(upgrade.id))records.push(boolRecord('island-upgrades',upgrade.id));
 const killed=new Map(dictionary(player,'stats > specificMonstersKilled').map(({key,node})=>[key,number(node,'value > int')]));for(const goal of MONSTER_SLAYER_GOALS){const count=goal.targets.reduce((sum,target)=>sum+(killed.get(target)||0),0);records.push({domain:'monster-goals',itemId:goal.id,value:{count,target:goal.count,completed:count>=goal.count}})}records.push({domain:'relationships',itemId:'household',value:{spouse:text(player,'spouse'),children:0,houseUpgrade:number(player,'houseUpgradeLevel')}});records.push({domain:'farmer',itemId:'overview',value:{totalMoneyEarned:number(player,'totalMoneyEarned'),millisecondsPlayed:number(player,'millisecondsPlayed'),questsCompleted:stat(player,'questsCompleted'),deepestMineLevel:number(player,'deepestMineLevel'),farmType:text(player,'farmName'),jojaMember:received.has('jojaMember')}});return{sourceId,name:text(player,'name',isHost?'Host':`Farmhand ${index}`),isHost,records}}
export async function parseSaveFile(file:File):Promise<NormalizedSaveImport>{if(file.size>20*1024*1024)throw new Error('Save files larger than 20 MB are not supported.');const xml=await file.text(),doc=new DOMParser().parseFromString(xml,'application/xml');if(doc.querySelector('parsererror')||!doc.querySelector('SaveGame'))throw new Error('This is not a valid Stardew Valley save XML file.');const root=doc.querySelector('SaveGame')!,gameVersion=text(root,'gameVersion','1.6.0');if(!/^1\.6(?:\.\d+)?$/.test(gameVersion))throw new Error(`Stardew ${gameVersion} is not supported. Junimo Journal currently supports 1.6.x saves.`);const platform=root.getAttribute('xmlns:xsi')||xml.includes('xmlns:xsi')?'PC':'Mobile';const host=root.querySelector(':scope > player');if(!host)throw new Error('The save does not contain a host farmer.');const hostMail=mailSet(host),bundle=parseBundleLayout(root,hostMail),farmhands=[parsePlayer(host,host,true,0),...items(root,'farmhands Farmer').map((node,index)=>parsePlayer(node,host,false,index+1))],shared:TrackerRecord[]=[{domain:'bundles',itemId:'layout',value:bundle.layout as unknown as Record<string,unknown>},...bundle.status];
 const children=new Map<string,Array<{name:string;age:number;gender:number}>>();for(const npc of items(root,'characters > NPC'))if(hasType(npc,'Child')){const parent=text(npc,'idOfParent'),rows=children.get(parent)||[];rows.push({name:text(npc,'name','Child'),age:number(npc,'daysOld',number(npc,'age')),gender:number(npc,'gender')});children.set(parent,rows)}const farmType=number(root,'whichFarm');for(const farmer of farmhands){const overview=farmer.records.find(r=>r.domain==='farmer'&&r.itemId==='overview');if(overview)overview.value.farmType=farmType;const household=farmer.records.find(r=>r.domain==='relationships'&&r.itemId==='household');if(household){const childDetails=children.get(farmer.sourceId)||[];household.value.children=childDetails.length;household.value.childDetails=childDetails}}
 for(const piece of items(root,'museumPieces > item')){const id=unqualifiedId(text(piece,'value > string')||text(piece,'value > int'));if(museumIds.has(id))shared.push(boolRecord('museum',id))}let obelisks=0,clock=false;for(const building of items(root,'buildings > Building')){const type=text(building,'buildingType');if(['Water Obelisk','Earth Obelisk','Desert Obelisk','Island Obelisk'].includes(type)&&number(building,'daysOfConstructionLeft')<=0)obelisks++;if(type==='Gold Clock'&&number(building,'daysOfConstructionLeft')<=0)clock=true}shared.push({domain:'perfection',itemId:'farm',value:{obelisks,clock,waivers:number(root,'perfectionWaivers')}});
 for(const animal of items(root,'FarmAnimal')){const name=text(animal,'name','Unknown'),type=text(animal,'type','Animal'),id=text(animal,'myID',`${type}-${name}`).replace(/[^a-zA-Z0-9-]/g,'-');shared.push({domain:'animals',itemId:id,value:{name,type,age:number(animal,'age'),friendship:number(animal,'friendshipTowardFarmer'),happiness:number(animal,'happiness'),kind:'farm'}})}for(const pet of items(root,'characters > NPC')){const type=text(pet,'petType');if(type)shared.push({domain:'animals',itemId:`pet-${normalizeId(text(pet,'name','Pet'))}`,value:{name:text(pet,'name','Pet'),type,friendship:number(pet,'friendshipTowardFarmer'),kind:'pet'}})}const horse=text(host,'horseName');if(horse)shared.push({domain:'animals',itemId:`horse-${normalizeId(horse)}`,value:{name:horse,type:'Horse',kind:'horse'}});
 const rarecrowIds=new Set<string>();for(const nameNode of items(root,'name'))if(nameNode.textContent?.trim()==='Rarecrow'){const parent=nameNode.parentElement,id=text(parent,'parentSheetIndex');if(id)rarecrowIds.add(id)}for(const id of rarecrowIds)if(rarecrowIdsCatalog.has(id))shared.push(boolRecord('rarecrows',id));const walnutCount=number(root,'goldenWalnutsFound',number(root,'GoldenWalnuts'));shared.push({domain:'walnuts',itemId:'total',value:{count:walnutCount,activatedGoldenParrot:text(root,'activatedGoldenParrot')==='true'}});for(const id of list(root,'collectedNutTracker > string'))if(walnutIds.has(id))shared.push({domain:'walnuts',itemId:id,value:{count:1}});const raccoonCompleted=number(root,'timesFedRaccoons');shared.push({domain:'raccoon',itemId:'progress',value:{requestsCompleted:raccoonCompleted}});for(const request of RACCOON_REQUESTS)if(request.order<=raccoonCompleted)shared.push(boolRecord('raccoon',request.id));
 const warnings:string[]=[];if(farmhands.length>1)warnings.push(`${farmhands.length} farmhands detected. Map each farmer you want to import.`);if(!bundle.layout.rooms.length&&bundle.layout.route==='community-center')warnings.push('No Community Center bundle layout was found.');const counts=new Map<string,number>();for(const record of [...shared,...farmhands.flatMap(x=>x.records)])counts.set(record.domain,(counts.get(record.domain)||0)+1);return{fileHash:await hashFile(xml),gameVersion,platform,farmName:text(root,'farmName',text(host,'farmName','My Farm')),season:seasonName(text(root,'currentSeason','spring')),day:number(root,'dayOfMonth',1),year:number(root,'year',1),route:bundle.layout.route,bundleKind:bundle.layout.kind,shared,farmhands,warnings,summary:[...counts].map(([domain,records])=>({domain,records}))}}