import {useEffect,useState,type ChangeEvent, type DragEvent} from 'react';
import type {NormalizedSaveImport} from '@stardew/game-data';
import {api,type Session} from '../api';
import {parseSaveFile} from '../lib/save-parser';
import UiIcon from './UiIcon';
import './save-import.css';
type Member={id:number;displayName:string;role:string};
export default function SaveImportModal({session,members,farmVersion,close,done}:{session:Session;members:Member[];farmVersion:number;close:()=>void;done:()=>void}){
 const[parsed,setParsed]=useState<NormalizedSaveImport|null>(null),[mappings,setMappings]=useState<Record<string,string>>({}),[updateName,setUpdateName]=useState(true),[updateDate,setUpdateDate]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[latest,setLatest]=useState<any>(null);
 useEffect(()=>{api.latestImport().then(setLatest).catch(()=>undefined)},[]);
 const read=async(file?:File)=>{if(!file)return;setBusy(true);setError('');try{const result=await parseSaveFile(file);setParsed(result);const next:Record<string,string>={};for(const farmer of result.farmhands){const matching=members.find(m=>m.displayName.toLowerCase()===farmer.name.toLowerCase());if(matching)next[farmer.sourceId]=String(matching.id);else if(result.farmhands.length===1&&session.user)next[farmer.sourceId]=String(session.user.id)}setMappings(next)}catch(e){setError(e instanceof Error?e.message:'Could not parse this save.')}finally{setBusy(false)}};
 const choose=(event:ChangeEvent<HTMLInputElement>)=>read(event.target.files?.[0]);
 const drop=(event:DragEvent)=>{event.preventDefault();read(event.dataTransfer.files?.[0])};
 const submit=async()=>{if(!parsed||!session.user)return;const selected=Object.entries(mappings).filter(([,id])=>id).map(([sourceId,userId])=>({sourceId,userId:Number(userId)}));if(!selected.length){setError('Map at least one farmhand to a journal account.');return}setBusy(true);setError('');try{await api.importSave({...parsed,farmVersion,updateName,updateDate,mappings:selected});done()}catch(e:any){setError(e.message||'Import failed.');setBusy(false)}};
 return <div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className="modal-card import-modal" role="dialog" aria-modal="true" aria-labelledby="import-title"><header><div><small>Private, local XML parser</small><h2 id="import-title"><UiIcon name="import"/> Import Stardew save</h2></div><button onClick={close} aria-label="Close import">×</button></header>
 {!parsed?<><label className="save-drop" onDragOver={e=>e.preventDefault()} onDrop={drop}><input type="file" accept=".xml,text/xml" onChange={choose}/><UiIcon name={busy?'refresh':'import'} label="Choose a save"/><span>{busy?'Reading your farm…':'Drop or choose your farmer save file'}</span><small>The raw XML stays in this browser and is never uploaded or stored.</small></label><details><summary>Where is my save?</summary><p><b>Windows:</b> %appdata%\StardewValley\Saves</p><p><b>macOS/Linux:</b> ~/.config/StardewValley/Saves</p><p><b>Android:</b> StardewValley/Saves in device storage</p><p>Choose the large file named after your farmer or farm, not <code>SaveGameInfo</code>.</p></details></>:<><div className="import-summary"><article><small>Farm</small><strong>{parsed.farmName}</strong><span>{parsed.season} {parsed.day}, Year {parsed.year}</span></article><article><small>Save</small><strong>{parsed.platform} · {parsed.gameVersion}</strong><span>{parsed.route==='joja'?'Joja route':`${parsed.bundleKind} bundles`}</span></article><article><small>Farmers</small><strong>{parsed.farmhands.length}</strong><span>{parsed.farmhands.reduce((n,p)=>n+p.records.length,0)} player records</span></article></div>
 <section className="import-domains" aria-label="Detected save data">{parsed.summary.map(row=><span key={row.domain}><b>{row.records}</b> {row.domain}</span>)}</section>
 {latest?.fileHash===parsed.fileHash&&<p className="import-warning"><UiIcon name="warning"/> This exact save was last imported {new Date(latest.importedAt).toLocaleString()}.</p>}
 <fieldset><legend>Map farmers to journal accounts</legend>{parsed.farmhands.map(farmer=><label key={farmer.sourceId}><span><b>{farmer.name}</b><small>{farmer.isHost?'Host farmer':'Farmhand'} · {farmer.records.length} records</small></span><select value={mappings[farmer.sourceId]||''} onChange={e=>setMappings({...mappings,[farmer.sourceId]:e.target.value})}><option value="">Do not import</option>{members.filter(m=>session.user?.role==='owner'||m.id===session.user?.id).map(member=><option key={member.id} value={member.id}>{member.displayName}</option>)}</select></label>)}</fieldset>
 <div className="import-options"><label><input type="checkbox" checked={updateName} onChange={e=>setUpdateName(e.target.checked)}/> Update farm name to “{parsed.farmName}”</label><label><input type="checkbox" checked={updateDate} onChange={e=>setUpdateDate(e.target.checked)}/> Update journal to {parsed.season} {parsed.day}, Year {parsed.year}</label></div>{parsed.warnings.map(w=><p className="import-warning" key={w}><UiIcon name="warning"/> {w}</p>)}</>}
 {error&&<p className="form-error">{error}</p>}<footer><button onClick={close}>Cancel</button>{parsed&&<button className="journal-primary" disabled={busy} onClick={submit}>{busy?'Importing…':'Apply import'}</button>}</footer></section></div>
}