import { useState } from 'react';
import { COOKING_RECIPES, CRAFTING_RECIPES, MUSEUM_ITEMS, SHIPPING_ITEMS } from '@stardew/game-data';
import GameIcon from '../components/GameIcon';
import './trackers.css';

type Entry={userId:number|null;scope:'shared'|'player';domain:string;itemId:string;value:any};
type Update={scope:'shared'|'player';domain:string;itemId:string;value:object};

export default function CollectionsTracker({entries,ownId,put,batch}:{entries:Entry[];ownId:number;put:(scope:'shared'|'player',domain:string,id:string,value:object)=>void;batch:(updates:Update[])=>void}) {
  const [section,setSection]=useState<'museum'|'shipping'|'cooking'|'crafting'>('museum'); const [query,setQuery]=useState(''); const [filter,setFilter]=useState<'all'|'missing'|'done'>('all');
  const datasets={museum:MUSEUM_ITEMS,shipping:SHIPPING_ITEMS,cooking:COOKING_RECIPES,crafting:CRAFTING_RECIPES} as const; const rows=datasets[section]; const player=section!=='museum';
  const complete=(id:string)=>entries.some((entry)=>entry.domain===section&&entry.itemId===id&&(!player||entry.userId===ownId)&&entry.value?.completed===true);
  const shown=rows.filter((row)=>row.name.toLowerCase().includes(query.toLowerCase())&&(filter==='all'||(filter==='done')===complete(row.id))); const done=rows.filter((row)=>complete(row.id)).length;
  const markVisible=()=>batch(shown.filter((row)=>!complete(row.id)).map((row)=>({scope:player?'player':'shared',domain:section,itemId:row.id,value:{completed:true}})));
  return <><header className="tab-intro"><h1>Collections</h1><p>Museum donations and perfection collections, manually editable or filled from a save.</p></header><nav className="tracker-segments">{(['museum','shipping','cooking','crafting'] as const).map((id)=><button className={section===id?'active':''} onClick={()=>{setSection(id);setQuery('')}} key={id}>{id[0].toUpperCase()+id.slice(1)}</button>)}</nav><section className="journal-card tracker-tools"><div className="tracker-meter"><span><b>{done}</b> of {rows.length}</span><div><i style={{width:`${rows.length?done/rows.length*100:0}%`}}/></div></div><div><input aria-label="Search collection" placeholder={`Search ${section}...`} value={query} onChange={(event)=>setQuery(event.target.value)}/><select aria-label="Collection status" value={filter} onChange={(event)=>setFilter(event.target.value as typeof filter)}><option value="all">All</option><option value="missing">Missing</option><option value="done">Complete</option></select><button disabled={!shown.some((row)=>!complete(row.id))} onClick={markVisible}>Mark visible complete</button></div></section><div className="collection-grid">{shown.map((row:any)=>{const checked=complete(row.id);return <article className={checked?'complete':''} key={row.id}><button className="sprite-check" onClick={()=>put(player?'player':'shared',section,row.id,{completed:!checked})} aria-label={`${checked?'Mark missing':'Mark complete'} ${row.name}`}><GameIcon src={row.iconPath} label={row.name}/><span>{checked?'✓':''}</span></button><div><strong>{row.name}</strong><small>{section==='museum'?row.category:row.unlock||row.description||'Stardew Valley collection item'}</small>{row.locations?.length>0&&<details><summary>Where to find it</summary><p>{row.locations.slice(0,3).join(' · ')}</p></details>}</div></article>})}</div>{!shown.length&&<p className="empty-note">No items match these filters.</p>}</>;
}
