import { useState } from 'react';
import { searchCatalog } from '@stardew/game-data';
import GameIcon from '../components/GameIcon';
import UiIcon from '../components/UiIcon';

export default function JournalReferenceTab({revealLateGame,reveal,hide}:{revealLateGame:boolean;reveal:()=>void;hide:()=>void}){
 const[query,setQuery]=useState('');const[confirm,setConfirm]=useState(false);const results=query.trim().length>1?searchCatalog(query,undefined,revealLateGame).slice(0,30):[];
 return <><header className="tab-intro"><h1>Verified reference</h1><p>Search crops, fish, villagers, bundles, buildings, calendar entries, and major collection milestones.</p></header><div className="reference-search"><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search for a crop, fish, gift, bundle, or building..." aria-label="Search the Stardew reference"/><span>⌕</span></div>{results.length>0&&<div className="reference-results">{results.map((record:any)=><article key={`${record.domain}:${record.id}`}><GameIcon src={record.iconPath} label={record.name} size={30}/><div><strong>{record.name}</strong><small>{record.domain} · {record.gameVersion}</small><p>{summary(record)}</p></div><a href={record.source} target="_blank" rel="noreferrer">Source ↗</a></article>)}</div>}{query.length>1&&!results.length&&<p className="empty-note">No spoiler-safe matches found.</p>}{revealLateGame?<button className="spoiler-reset" onClick={hide}>Hide late-game details again</button>:<section className="spoiler-gate"><UiIcon name="warning"/><div><strong>Late-game details are tucked away</strong><p>This search omits future locations, people, and progression systems.</p></div>{confirm?<div className="spoiler-confirm"><button onClick={()=>setConfirm(false)}>Keep hidden</button><button className="danger" onClick={reveal}>Reveal late-game details</button></div>:<button onClick={()=>setConfirm(true)}>Show warning</button>}</section>}</>;
}
function summary(record:any){if(record.materials)return Object.entries(record.materials).map(([name,count])=>`${count} ${name}`).join(' · ');if(record.birthday)return`Birthday: ${record.birthday.season} ${record.birthday.day}`;if(record.seasons)return record.seasons.join(' · ');if(record.reward)return`Reward: ${record.reward}`;return record.description||''}
