import { useState } from 'react';
import { ISLAND_UPGRADES, MONSTER_SLAYER_GOALS, RACCOON_REQUESTS, WALNUT_SOURCES } from '@stardew/game-data';
import GameIcon from '../components/GameIcon';
import './trackers.css';

type Entry={userId:number|null;scope:'shared'|'player';domain:string;itemId:string;value:any};
type Put=(scope:'shared'|'player',domain:string,id:string,value:object)=>void;

export default function LateGameTracker({ entries, ownId, put }: { entries: Entry[]; ownId: number; put: Put }) {
  const [section, setSection] = useState<'monsters'|'walnuts'|'upgrades'|'raccoon'>('monsters');
  const value = (domain:string,id:string,player=false) => entries.find((entry) => entry.domain === domain && entry.itemId === id && (!player || entry.userId === ownId))?.value;
  return <><header className="tab-intro"><h1>Late-game progress</h1><p>Private, manually editable trackers. Save imports fill supported records without revealing unrelated discoveries.</p></header><nav className="tracker-segments">{([['monsters','Monster goals'],['walnuts','Golden Walnuts'],['upgrades','Island upgrades'],['raccoon','Raccoon requests']] as const).map(([id,label]) => <button className={section === id ? 'active' : ''} onClick={() => setSection(id)} key={id}>{label}</button>)}</nav>
  {section === 'monsters' && <div className="collection-grid">{MONSTER_SLAYER_GOALS.map((goal) => { const count = Math.min(goal.count, Number(value('monster-goals',goal.id,true)?.count || 0)); return <article className={count >= goal.count ? 'complete' : ''} key={goal.id}><GameIcon label={goal.name}/><div><strong>{goal.name}</strong><small>{goal.targets.join(' · ')}</small><label>Defeated <input type="number" min={0} max={goal.count} value={count} onChange={(event) => put('player','monster-goals',goal.id,{count:Math.max(0,Math.min(goal.count,Number(event.target.value))),completed:Number(event.target.value)>=goal.count})}/><span>/ {goal.count}</span></label></div></article>; })}</div>}
  {section === 'walnuts' && <div className="collection-grid">{WALNUT_SOURCES.map((source) => { const count = Math.min(source.count, Number(value('walnuts',source.id)?.count || 0)); return <article className={count >= source.count ? 'complete' : ''} key={source.id}><div><strong>{source.name}</strong><small>{source.description}</small><div className="heart-stepper"><button disabled={count <= 0} aria-label={`Lower ${source.name} count`} onClick={() => put('shared','walnuts',source.id,{count:count-1,completed:false})}>−</button><b>{count}/{source.count}</b><button disabled={count >= source.count} aria-label={`Raise ${source.name} count`} onClick={() => put('shared','walnuts',source.id,{count:count+1,completed:count+1>=source.count})}>+</button></div></div></article>; })}</div>}
  {section === 'upgrades' && <div className="collection-grid">{ISLAND_UPGRADES.map((upgrade) => { const completed = value('island-upgrades',upgrade.id,true)?.completed === true; return <article className={completed ? 'complete' : ''} key={upgrade.id}><button className="sprite-check" aria-label={`${completed?'Mark incomplete':'Mark complete'} ${upgrade.name}`} onClick={() => put('player','island-upgrades',upgrade.id,{completed:!completed})}><GameIcon src={upgrade.iconPath} label={upgrade.name}/><span>{completed?'✓':''}</span></button><div><strong>{upgrade.name}</strong><small>{upgrade.description}</small></div></article>; })}</div>}
  {section === 'raccoon' && <div className="collection-grid">{RACCOON_REQUESTS.map((request) => { const completed = value('raccoon',request.id)?.completed === true; return <article className={completed ? 'complete' : ''} key={request.id}><button className="sprite-check" aria-label={`${completed?'Mark incomplete':'Mark complete'} ${request.name}`} onClick={() => put('shared','raccoon',request.id,{completed:!completed})}><span>{completed?'✓':''}</span></button><div><strong>{request.name}</strong><small>{request.request}</small><p>Reward: {request.reward}</p></div></article>; })}</div>}</>;
}
