import { meta } from './meta.js';
import type { Project } from './types.js';
const b=meta('Carpenter%27s_Shop'),c=meta('Crafting');
const lateIds=new Set(['willy-boat','desert-obelisk','island-obelisk','gold-clock']);
const icons:Record<string,string>={silo:'/game-icons/buildings/silo.png',coop:'/game-icons/buildings/coop.png','big-coop':'/game-icons/buildings/big-coop.png','deluxe-coop':'/game-icons/buildings/deluxe-coop.png',barn:'/game-icons/buildings/barn.png','big-barn':'/game-icons/buildings/big-barn.png','deluxe-barn':'/game-icons/buildings/deluxe-barn.png','fish-pond':'/game-icons/buildings/fish-pond.png',mill:'/game-icons/buildings/mill.png',shed:'/game-icons/buildings/shed.png',stable:'/game-icons/buildings/stable.png','slime-hutch':'/game-icons/buildings/slime-hutch.png',well:'/game-icons/buildings/well.png','cheese-press':'/game-icons/big-craftables/16.webp','seed-maker':'/game-icons/big-craftables/25.webp','recycling-machine':'/game-icons/big-craftables/20.webp',keg:'/game-icons/big-craftables/12.webp','preserves-jar':'/game-icons/big-craftables/15.webp',dehydrator:'/game-icons/big-craftables/Dehydrator.webp','fish-smoker':'/game-icons/big-craftables/FishSmoker.webp','willy-boat':'/game-icons/objects/787.webp','desert-obelisk':'/game-icons/buildings/desert-obelisk.png','island-obelisk':'/game-icons/buildings/island-obelisk.png','gold-clock':'/game-icons/buildings/gold-clock.png'};
const p=(id:string,name:string,emoji:string,category:Project['category'],materials:Record<string,number>,cost?:number,prerequisite?:string,source=b.source):Project=>({...b,source,id,name,emoji,iconPath:icons[id],category,materials,cost,prerequisite,spoilerTier:lateIds.has(id)?'late-game':category==='unlock'||category==='perfection'?'progression':'ordinary'});
export const PROJECTS:Project[]=[
 p('silo','Silo','🏭','building',{Stone:100,Clay:10,'Copper Bar':5},100),p('coop','Coop','🐔','building',{Wood:300,Stone:100},4000),p('big-coop','Big Coop','🐔','building',{Wood:400,Stone:150},10000,'Coop'),p('deluxe-coop','Deluxe Coop','🐇','building',{Wood:500,Stone:200},20000,'Big Coop'),p('barn','Barn','🐄','building',{Wood:350,Stone:150},6000),p('big-barn','Big Barn','🐐','building',{Wood:450,Stone:200},12000,'Barn'),p('deluxe-barn','Deluxe Barn','🐖','building',{Wood:550,Stone:300},25000,'Big Barn'),p('fish-pond','Fish Pond','🐟','building',{Stone:200,Seaweed:5,'Green Algae':5},5000),p('mill','Mill','⚙️','building',{Stone:50,Wood:150,Cloth:4},2500),p('shed','Shed','🏠','building',{Wood:300},15000),p('stable','Stable','🐎','building',{Hardwood:100,'Iron Bar':5},10000),p('slime-hutch','Slime Hutch','💚','building',{Stone:500,'Refined Quartz':10,'Iridium Bar':1},10000),p('well','Well','🪣','building',{Stone:75},1000),
 p('cheese-press','Cheese Press','🧀','machine',{Wood:45,Stone:45,Hardwood:10,'Copper Bar':1},undefined,'Farming Level 6',c.source),p('seed-maker','Seed Maker','🌱','machine',{Wood:25,'Gold Bar':1,Coal:10},undefined,'Farming Level 9',c.source),p('recycling-machine','Recycling Machine','♻️','machine',{Wood:25,Stone:25,'Iron Bar':1},undefined,'Fishing Level 4',c.source),p('keg','Keg','🍷','machine',{Wood:30,'Copper Bar':1,'Iron Bar':1,'Oak Resin':1},undefined,'Farming Level 8',c.source),p('preserves-jar','Preserves Jar','🫙','machine',{Wood:50,Stone:40,Coal:8},undefined,'Farming Level 4',c.source),p('dehydrator','Dehydrator','🍇','machine',{Wood:30,Clay:2,'Fire Quartz':1},undefined,'Recipe from Pierre',c.source),p('fish-smoker','Fish Smoker','🐟','machine',{Hardwood:10,'Sea Jelly':1,'River Jelly':1,'Cave Jelly':1},undefined,'Recipe from Willy',c.source),
 p('willy-boat',"Willy’s Boat",'⛵','unlock',{Hardwood:200,'Battery Pack':5,'Iridium Bar':5},undefined,'Complete the Community Center or Joja improvements',meta('Ginger_Island').source),p('desert-obelisk','Desert Obelisk','🏜️','perfection',{'Iridium Bar':20,Coconut:10,'Cactus Fruit':10},1000000,'Wizard buildings'),p('island-obelisk','Island Obelisk','🏝️','perfection',{'Iridium Bar':10,'Dragon Tooth':10,Banana:10},1000000,'Wizard buildings'),p('gold-clock','Gold Clock','🕰️','perfection',{},10000000,'Wizard buildings'),
];
