import crypto from 'node:crypto';import type { NextFunction,Request,Response } from 'express';import { db,userBySession,type AuthUser } from './db.js';import { config } from './config.js';
declare global{namespace Express{interface Request{user?:AuthUser}}}
export const hashToken=(value:string)=>crypto.createHash('sha256').update(value).digest('hex');
export function createSession(userId:number,res:Response){const raw=crypto.randomBytes(32).toString('base64url');const now=new Date();const expires=new Date(now.getTime()+30*86400000);db.prepare('INSERT INTO sessions(token_hash,user_id,expires_at,created_at) VALUES(?,?,?,?)').run(hashToken(raw),userId,expires.toISOString(),now.toISOString());res.cookie('stardew_session',raw,{httpOnly:true,secure:config.secureCookies,sameSite:'lax',path:'/',expires});}
export function attachUser(req:Request,_res:Response,next:NextFunction){const raw=req.cookies?.stardew_session;if(raw)req.user=userBySession(hashToken(raw));next()}
export function requireAuth(req:Request,res:Response,next:NextFunction){if(!req.user)return res.status(401).json({error:'Authentication required'});next()}
export function sameOrigin(req:Request,res:Response,next:NextFunction){if(['GET','HEAD','OPTIONS'].includes(req.method))return next();const origin=req.get('origin');const host=req.get('host');if(origin&&new URL(origin).host!==host)return res.status(403).json({error:'Cross-origin request blocked'});next()}
const buckets=new Map<string,{count:number;reset:number}>();
export function rateLimit(limit:number,windowMs:number){return(req:Request,res:Response,next:NextFunction)=>{const key=`${req.ip}:${req.user?.id||'guest'}:${req.path}`;const now=Date.now();let b=buckets.get(key);if(!b||b.reset<now)b={count:0,reset:now+windowMs};b.count++;buckets.set(key,b);if(b.count>limit)return res.status(429).json({error:'Too many requests',retryAfter:Math.ceil((b.reset-now)/1000)});next()}}
