import{Router}from'express';import{z}from'zod';import{db}from'./db.js';import{requireAuth}from'./auth.js';
export const importRouter=Router();
db.exec(`CREATE TABLE IF NOT EXISTS save_imports(id INTEGER PRIMARY KEY,farm_id INTEGER NOT NULL REFERENCES farms(id) ON DELETE CASCADE,imported_by INTEGER NOT NULL REFERENCES users(id),file_hash TEXT NOT NULL,game_version TEXT NOT NULL,summary_json TEXT NOT NULL,created_at TEXT NOT NULL);CREATE INDEX IF NOT EXISTS save_imports_farm_time ON save_imports(farm_id,created_at DESC);INSERT OR IGNORE INTO schema_migrations(version,applied_at) VALUES(2,datetime('now'));`);
const domains=['museum','shipping','cooking','crafting','fish','relationships','animals','skills','stardrops','monster-goals','walnuts','perfection','bundles']as const;
const record=z.object({domain:z.enum(domains),itemId:z.string().min(1).max(160),value:z.record(z.unknown())});
const payload=z.object({fileHash:z.string().regex(/^[a-f0-9]{64}$/),gameVersion:z.string().regex(/^1\.6(?:\.\d+)?$/),farmName:z.string().min(1).max(50),season:z.enum(['Spring','Summer','Fall','Winter']),day:z.number().int().min(1).max(28),year:z.number().int().min(1).max(999),farmVersion:z.number().int().min(1),updateName:z.boolean(),updateDate:z.boolean(),shared:z.array(record).max(1200),farmhands:z.array(z.object({sourceId:z.string().min(1).max(80),name:z.string().min(1).max(60),isHost:z.boolean(),records:z.array(record).max(1500)})).max(8),mappings:z.array(z.object({sourceId:z.string(),userId:z.number().int().positive()})).max(8),warnings:z.array(z.string().max(200)).max(30).default([])}).strict();
const now=()=>new Date().toISOString();
const upsert=db.prepare('INSERT INTO progress(farm_id,user_id,scope,domain,item_id,value_json,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT DO UPDATE SET value_json=excluded.value_json,updated_at=excluded.updated_at');

importRouter.get('/latest',requireAuth,(req,res)=>{const row=db.prepare('SELECT file_hash fileHash,game_version gameVersion,summary_json summary,created_at importedAt FROM save_imports WHERE farm_id=? ORDER BY id DESC LIMIT 1').get(req.user!.farmId)as any;if(row)row.summary=JSON.parse(row.summary);res.json(row||null)});
importRouter.post('/save',requireAuth,(req,res)=>{const input=payload.parse(req.body);const current=db.prepare('SELECT f.name,s.season,s.year,s.day,s.version FROM farms f JOIN farm_state s ON s.farm_id=f.id WHERE f.id=?').get(req.user!.farmId)as any;if(!current)return res.status(404).json({error:'Farm not found'});if(current.version!==input.farmVersion)return res.status(409).json({error:'Farm changed in another session',current});
 const members=db.prepare('SELECT user_id id FROM farm_members WHERE farm_id=?').all(req.user!.farmId)as Array<{id:number}>;const memberIds=new Set(members.map(x=>x.id));const sourceIds=new Set(input.farmhands.map(x=>x.sourceId));if(new Set(input.mappings.map(x=>x.sourceId)).size!==input.mappings.length||new Set(input.mappings.map(x=>x.userId)).size!==input.mappings.length)return res.status(400).json({error:'Each farmhand and account can only be mapped once'});for(const map of input.mappings){if(!memberIds.has(map.userId)||!sourceIds.has(map.sourceId))return res.status(400).json({error:'Invalid farmhand mapping'});if(req.user!.role!=='owner'&&map.userId!==req.user!.id)return res.status(403).json({error:'Only the owner can import another farmer'});}if(req.user!.role!=='owner'&&(input.mappings.length!==1||input.mappings[0].userId!==req.user!.id))return res.status(403).json({error:'Choose your own farmhand'});
 const stamp=now();const counts:Record<string,number>={};const apply=db.transaction(()=>{const sharedDomains=[...new Set(input.shared.map(row=>row.domain))];for(const domain of sharedDomains)db.prepare("DELETE FROM progress WHERE farm_id=? AND user_id IS NULL AND scope='shared' AND domain=? AND json_extract(value_json,'$.source')='save'").run(req.user!.farmId,domain);for(const row of input.shared){const value={...row.value,source:'save',importHash:input.fileHash};upsert.run(req.user!.farmId,null,'shared',row.domain,row.itemId,JSON.stringify(value),stamp);counts[row.domain]=(counts[row.domain]||0)+1}for(const map of input.mappings){const farmer=input.farmhands.find(x=>x.sourceId===map.sourceId)!;const touched=[...new Set(farmer.records.map(x=>x.domain))];for(const domain of touched)db.prepare("DELETE FROM progress WHERE farm_id=? AND user_id=? AND scope='player' AND domain=? AND json_extract(value_json,'$.source')='save'").run(req.user!.farmId,map.userId,domain);for(const row of farmer.records){const value={...row.value,source:'save',importHash:input.fileHash,sourceFarmhand:map.sourceId};upsert.run(req.user!.farmId,map.userId,'player',row.domain,row.itemId,JSON.stringify(value),stamp);counts[row.domain]=(counts[row.domain]||0)+1}}if(input.updateName)db.prepare('UPDATE farms SET name=? WHERE id=?').run(input.farmName,req.user!.farmId);if(input.updateDate)db.prepare('UPDATE farm_state SET season=?,year=?,day=? WHERE farm_id=?').run(input.season,input.year,input.day,req.user!.farmId);db.prepare('UPDATE farm_state SET version=version+1,updated_at=? WHERE farm_id=?').run(stamp,req.user!.farmId);const summary={counts,mappings:input.mappings.length,warnings:input.warnings};db.prepare('INSERT INTO save_imports(farm_id,imported_by,file_hash,game_version,summary_json,created_at) VALUES(?,?,?,?,?,?)').run(req.user!.farmId,req.user!.id,input.fileHash,input.gameVersion,JSON.stringify(summary),stamp);return summary});const summary=apply();res.json({ok:true,version:current.version+1,summary,importedAt:stamp})});
