export type Session={user:null|{id:number;username:string;displayName:string;farmId:number;role:'owner'|'member'};setupRequired:boolean};
export type SaveState='idle'|'saving'|'saved'|'retrying'|'offline'|'failed';
export type ProgressUpdate={scope:'shared'|'player';domain:string;itemId:string;value:object};
async function request<T>(path:string,init?:RequestInit):Promise<T>{try{const res=await fetch(`/api${path}`,{...init,headers:{'Content-Type':'application/json',...(init?.headers||{})}});const body=res.status===204?null:await res.json();if(!res.ok){const details=Array.isArray(body?.issues)?body.issues.slice(0,3).map((issue:any)=>`${issue.path?.join('.')||'save'}: ${issue.message}`).join(' | '):'';throw Object.assign(new Error(details?`${body?.error||'Invalid request'}: ${details}`:body?.error||'Request failed'),{status:res.status,body})}return body}catch(error){if(!navigator.onLine)throw Object.assign(error as Error,{offline:true});throw error}}
export const api={
 session:()=>request<Session>('/auth/session'),setup:(data:object)=>request('/auth/setup',{method:'POST',body:JSON.stringify(data)}),login:(data:object)=>request('/auth/login',{method:'POST',body:JSON.stringify(data)}),logout:()=>request('/auth/logout',{method:'POST'}),invite:(data:object)=>request('/auth/invite',{method:'POST',body:JSON.stringify(data)}),
 farms:()=>request<any>('/farms'),createFarm:(name:string,memberIds:number[])=>request<any>('/farms',{method:'POST',body:JSON.stringify({name,memberIds})}),activateFarm:(farmId:number)=>request(`/farms/${farmId}/active`,{method:'PUT'}),
 farm:()=>request<any>('/farm'),updateFarm:(data:object)=>request<any>('/farm',{method:'PATCH',body:JSON.stringify(data)}),updateFarmSettings:(revealLateGame:boolean)=>request<any>('/farm/settings',{method:'PATCH',body:JSON.stringify({revealLateGame})}),catalog:(domain:string,q='')=>request<any>(`/catalog/${domain}?q=${encodeURIComponent(q)}`),
 progress:(domains:string[],players:'self'|'farm'='self')=>request<any[]>(`/progress?domains=${encodeURIComponent(domains.join(','))}&players=${players}`),putProgress:(scope:string,domain:string,itemId:string,value:object)=>request(`/progress/${scope}/${domain}/${encodeURIComponent(itemId)}`,{method:'PUT',body:JSON.stringify(value)}),batchProgress:(entries:ProgressUpdate[])=>request<any>('/progress/batch',{method:'PUT',body:JSON.stringify({entries})}),
 goals:()=>request<any[]>('/goals'),addGoal:(data:object)=>request('/goals',{method:'POST',body:JSON.stringify(data)}),updateGoal:(id:number,completed:boolean)=>request(`/goals/${id}`,{method:'PATCH',body:JSON.stringify({completed})}),deleteGoal:(id:number)=>request(`/goals/${id}`,{method:'DELETE'}),dailyPlan:()=>request<any>('/ai/daily-plan',{method:'POST'}),chat:(question:string,concise=false)=>request<any>('/ai/chat',{method:'POST',body:JSON.stringify({question,concise})}),
 latestImport:()=>request<any>('/imports/latest'),importSave:(data:object)=>request<any>('/imports/save',{method:'POST',body:JSON.stringify(data)}),
};
